import { StyleSheet } from "react-native";
import { theme, type Palette } from "@styles/theme";

export const makeMealsStyles = (palette: Palette) =>
  StyleSheet.create({
    screen: {
      flex: 1,
      backgroundColor: palette.background,
    },
    header: {
      paddingHorizontal: 16,
      paddingTop: 20,
      paddingBottom: 10,
    },
    title: {
      fontSize: 24,
      fontWeight: "700",
      color: palette.text,
      marginBottom: 16,
    },
    tabs: {
      flexDirection: "row",
      marginBottom: 16,
      backgroundColor: palette.card,
      borderRadius: theme.radius.lg,
      padding: 4,
    },
    tab: {
      flex: 1,
      paddingVertical: 10,
      alignItems: "center",
      borderRadius: theme.radius.md,
    },
    activeTab: {
      backgroundColor: palette.primary,
    },
    tabText: {
      fontWeight: "600",
      color: palette.subText,
    },
    activeTabText: {
      color: palette.onPrimary,
    },
    section: {
      marginBottom: 24,
    },
    sectionHeader: {
      flexDirection: "row",
      justifyContent: "space-between",
      alignItems: "center",
      marginBottom: 12,
      paddingHorizontal: 16,
    },
    sectionTitle: {
      fontSize: 18,
      fontWeight: "700",
      color: palette.text,
    },
    sectionMeta: {
      fontSize: 14,
      color: palette.subText,
    },
    card: {
      backgroundColor: palette.card,
      borderRadius: theme.radius.lg,
      padding: 16,
      marginHorizontal: 16,
      marginBottom: 12,
      borderWidth: 1,
      borderColor: palette.border,
      flexDirection: "row",
      justifyContent: "space-between",
      alignItems: "center",
    },
    cardContent: {
      flex: 1,
    },
    cardTitle: {
      fontSize: 16,
      fontWeight: "600",
      color: palette.text,
    },
    cardSubtitle: {
      fontSize: 13,
      color: palette.subText,
      marginTop: 4,
    },
    actions: {
      flexDirection: "row",
      alignItems: "center",
    },
    actionBtn: {
      padding: 8,
      marginLeft: 8,
    },
    modalBg: {
      flex: 1,
      backgroundColor: palette.overlay,
      justifyContent: "center",
      padding: 24,
    },
    modal: {
      backgroundColor: palette.card100,
      borderRadius: theme.radius.lg,
      padding: 20,
      maxHeight: "80%",
    },
    modalTitle: {
      fontSize: 20,
      fontWeight: "700",
      color: palette.text,
      marginBottom: 20,
      textAlign: "center",
    },
    input: {
      backgroundColor: palette.background,
      color: palette.text,
      padding: 12,
      borderRadius: theme.radius.md,
      borderWidth: 1,
      borderColor: palette.border,
      marginBottom: 12,
    },
    btn: {
      backgroundColor: palette.primary,
      padding: 14,
      borderRadius: theme.radius.md,
      alignItems: "center",
      marginTop: 8,
    },
    btnText: {
      color: palette.onPrimary,
      fontWeight: "700",
      fontSize: 16,
    },
    cancelBtn: {
      padding: 14,
      alignItems: "center",
      marginTop: 8,
    },
    cancelBtnText: {
      color: palette.subText,
      fontWeight: "600",
    },
    summaryBox: {
      backgroundColor: palette.card,
      margin: 16,
      padding: 16,
      borderRadius: theme.radius.lg,
      borderWidth: 1,
      borderColor: palette.border,
    },
    summaryRow: {
      flexDirection: "row",
      justifyContent: "space-between",
      marginBottom: 8,
    },
    summaryLabel: {
      color: palette.subText,
      fontSize: 14,
    },
    summaryValue: {
      color: palette.text,
      fontWeight: "700",
      fontSize: 14,
    },
    emptyText: {
      textAlign: "center",
      color: palette.subText,
      marginTop: 20,
      fontStyle: "italic",
    },
    typeSelector: {
      flexDirection: "row",
      flexWrap: "wrap",
      gap: 8,
      marginBottom: 16,
    },
    typeBtn: {
      paddingVertical: 8,
      paddingHorizontal: 12,
      borderRadius: 20,
      borderWidth: 1,
      borderColor: palette.border,
      backgroundColor: palette.background,
    },
    typeBtnActive: {
      backgroundColor: palette.primary,
      borderColor: palette.primary,
    },
    typeBtnText: {
      color: palette.subText,
      fontSize: 13,
    },
    typeBtnTextActive: {
      color: palette.onPrimary,
      fontWeight: "600",
    },
    topButtons: {
      flexDirection: "row",
      flexWrap: "wrap",
      justifyContent: "space-between",
      marginBottom: 12,
    },
    smallBtn: {
      width: "32%",
      paddingVertical: 12,
      paddingHorizontal: 12,
      borderRadius: theme.radius.md,
      borderWidth: 1,
      borderColor: palette.border,
      backgroundColor: palette.card,
      alignItems: "center",
      marginBottom: 10,
    },
    smallBtnLast: {
      marginBottom: 0,
    },
    smallBtnText: {
      fontWeight: "600",
      color: palette.text,
      fontSize: 12,
    },
    scannerFab: {
      position: "absolute",
      right: 20,
      bottom: 24,
      backgroundColor: palette.primary,
      width: 56,
      height: 56,
      borderRadius: 28,
      alignItems: "center",
      justifyContent: "center",
      elevation: 6,
      shadowColor: "#000",
      shadowOffset: { width: 0, height: 4 },
      shadowOpacity: 0.25,
      shadowRadius: 6,
    },
    smallBtnAccent: {
      backgroundColor: palette.primary,
      borderColor: palette.primary,
    },
    smallBtnAccentText: {
      color: palette.onPrimary,
    },
    generatorBox: {
      backgroundColor: palette.card,
      borderWidth: 1,
      borderColor: palette.border,
      borderRadius: theme.radius.lg,
      padding: 16,
      marginBottom: 20,
    },
    generatorTitle: {
      fontSize: 18,
      fontWeight: "700",
      color: palette.text,
      marginBottom: 16,
    },
    row: {
      flexDirection: "row",
      alignItems: "center",
      flexWrap: "wrap",
      marginBottom: 12,
    },
    label: {
      color: palette.text,
      fontWeight: "600",
      marginRight: 12,
    },
    toggle: {
      flexBasis: "32%",
      alignItems: "center",
      paddingVertical: 10,
      borderRadius: theme.radius.md,
      borderWidth: 1,
      borderColor: palette.border,
      backgroundColor: palette.card100,
      marginRight: 10,
      marginBottom: 10,
    },
    toggleLast: {
      marginRight: 0,
    },
    toggleOn: {
      backgroundColor: palette.primary,
      borderColor: palette.primary,
    },
    toggleText: {
      fontWeight: "600",
      color: palette.text,
      fontSize: 11,
    },
    toggleTextOn: {
      color: palette.onPrimary,
    },
    addButton: {
      marginTop: 12,
      paddingVertical: 14,
      borderRadius: theme.radius.lg,
      backgroundColor: palette.primary,
      alignItems: "center",
    },
    addButtonText: {
      color: palette.onPrimary,
      fontSize: 16,
      fontWeight: "700",
    },
    generatedBox: {
      marginTop: 20,
      backgroundColor: palette.card,
      borderWidth: 1,
      borderColor: palette.border,
      borderRadius: theme.radius.lg,
      padding: 16,
    },
    generatedHeader: {
      flexDirection: "row",
      justifyContent: "space-between",
      alignItems: "center",
    },
    generatedTitle: {
      fontSize: 16,
      fontWeight: "700",
      color: palette.text,
    },
    clearGenerated: {
      color: palette.primary,
      fontWeight: "700",
    },
    summaryText: {
      marginTop: 8,
      fontWeight: "700",
      color: palette.text,
    },
    generatedItem: {
      marginTop: 8,
      paddingVertical: 8,
      borderBottomWidth: 1,
      borderBottomColor: palette.border,
    },
    muted: {
      color: palette.subText,
      marginTop: 8,
    },
    mealName: {
      fontSize: 16,
      fontWeight: "700",
      color: palette.text,
    },
    mealInfo: {
      fontSize: 13,
      marginTop: 4,
      color: palette.text,
    },
    defaultBadge: {
      marginTop: 6,
      color: palette.primary,
      fontWeight: "700",
      fontSize: 12,
    },
    flagsRow: {
      flexDirection: "row",
      flexWrap: "wrap",
      gap: 8,
      marginTop: 12,
      marginBottom: 4,
    },
    flagBtn: {
      paddingVertical: 8,
      paddingHorizontal: 12,
      borderRadius: 14,
      borderWidth: 1,
      borderColor: palette.border,
      backgroundColor: palette.card100,
    },
    flagBtnActive: {
      borderColor: palette.primary,
      backgroundColor: palette.primary,
    },
    flagText: {
      color: palette.text,
      fontSize: 12,
      fontWeight: "600",
    },
    flagTextActive: {
      color: palette.onPrimary,
    },
    defaultCard: {
      backgroundColor: palette.card,
      borderWidth: 1,
      borderColor: palette.border,
      borderRadius: theme.radius.lg,
      padding: 12,
      marginTop: 10,
    },
    defaultCardHeader: {
      flexDirection: "row",
      justifyContent: "space-between",
      alignItems: "center",
    },
    defaultCardTitle: {
      color: palette.text,
      fontWeight: "700",
      fontSize: 15,
    },
    defaultTags: {
      flexDirection: "row",
      flexWrap: "wrap",
      gap: 8,
      marginTop: 6,
      marginBottom: 6,
    },
    tag: {
      paddingHorizontal: 10,
      paddingVertical: 4,
      borderRadius: 12,
      backgroundColor: palette.card100,
      borderWidth: 1,
      borderColor: palette.border,
      color: palette.subText,
      fontSize: 11,
      fontWeight: "600",
    },
    defaultAddBtn: {
      marginTop: 8,
      alignSelf: "flex-start",
      backgroundColor: palette.primary,
      paddingVertical: 8,
      paddingHorizontal: 12,
      borderRadius: theme.radius.md,
    },
    defaultAddBtnText: {
      color: palette.onPrimary,
      fontWeight: "700",
      fontSize: 12,
    },
    defaultSection: {
      marginTop: 16,
    },
    defaultSectionHeader: {
      flexDirection: "row",
      justifyContent: "space-between",
      alignItems: "center",
      marginTop: 4,
      marginBottom: 6,
    },
    defaultSectionTitle: {
      fontSize: 16,
      fontWeight: "700",
      color: palette.text,
    },
    defaultSectionHint: {
      color: palette.subText,
      fontSize: 12,
    },
    addDefaultBtn: {
      marginTop: 12,
      paddingVertical: 12,
      borderRadius: theme.radius.lg,
      borderWidth: 1,
      borderColor: palette.primary,
      backgroundColor: palette.card,
      alignItems: "center",
    },
    addDefaultBtnText: {
      color: palette.primary,
      fontSize: 15,
      fontWeight: "700",
    },
  });
