import type { FoodItem } from '@models/MealModel';

export const DEFAULT_FOODS: FoodItem[] = [
  { id: 'default-01', user_id: 'default', is_default: true, name: 'Oatmeal with banana', calories: 350, protein: 12, carbs: 60, fat: 8, vegetarian: true, gluten_free: false, lactose_free: true },
  { id: 'default-02', user_id: 'default', is_default: true, name: 'Scrambled eggs with veggies', calories: 280, protein: 18, carbs: 10, fat: 18, vegetarian: true, gluten_free: true, lactose_free: true },
  { id: 'default-03', user_id: 'default', is_default: true, name: 'Protein omelette', calories: 320, protein: 28, carbs: 14, fat: 16, vegetarian: true, gluten_free: true, lactose_free: true },
  { id: 'default-04', user_id: 'default', is_default: true, name: 'Avocado toast with egg', calories: 420, protein: 18, carbs: 40, fat: 20, vegetarian: true, gluten_free: false, lactose_free: true },
  { id: 'default-05', user_id: 'default', is_default: true, name: 'Greek yogurt with honey', calories: 300, protein: 18, carbs: 30, fat: 10, vegetarian: true, gluten_free: true, lactose_free: false },
  { id: 'default-06', user_id: 'default', is_default: true, name: 'Cottage cheese with tomato', calories: 220, protein: 20, carbs: 8, fat: 12, vegetarian: true, gluten_free: true, lactose_free: false },
  { id: 'default-07', user_id: 'default', is_default: true, name: 'Protein shake (water)', calories: 200, protein: 30, carbs: 10, fat: 4, vegetarian: true, gluten_free: true, lactose_free: true },
  { id: 'default-08', user_id: 'default', is_default: true, name: 'Protein shake (milk)', calories: 260, protein: 32, carbs: 18, fat: 6, vegetarian: true, gluten_free: true, lactose_free: false },
  { id: 'default-09', user_id: 'default', is_default: true, name: 'Chicken with rice and broccoli', calories: 520, protein: 45, carbs: 60, fat: 10, vegetarian: false, gluten_free: true, lactose_free: true },
  { id: 'default-10', user_id: 'default', is_default: true, name: 'Salmon with sweet potato and asparagus', calories: 600, protein: 40, carbs: 50, fat: 22, vegetarian: false, gluten_free: true, lactose_free: true },
  { id: 'default-11', user_id: 'default', is_default: true, name: 'Turkey with bulgur', calories: 540, protein: 42, carbs: 58, fat: 14, vegetarian: false, gluten_free: false, lactose_free: true },
  { id: 'default-12', user_id: 'default', is_default: true, name: 'Beef with wholegrain pasta', calories: 650, protein: 45, carbs: 70, fat: 20, vegetarian: false, gluten_free: false, lactose_free: true },
  { id: 'default-13', user_id: 'default', is_default: true, name: 'Tofu stir-fry with rice', calories: 520, protein: 30, carbs: 62, fat: 16, vegetarian: true, gluten_free: true, lactose_free: true },
  { id: 'default-14', user_id: 'default', is_default: true, name: 'Shrimp with jasmine rice', calories: 480, protein: 38, carbs: 60, fat: 8, vegetarian: false, gluten_free: true, lactose_free: true },
  { id: 'default-15', user_id: 'default', is_default: true, name: 'Tuna with pasta', calories: 520, protein: 42, carbs: 64, fat: 10, vegetarian: false, gluten_free: false, lactose_free: true },
  { id: 'default-16', user_id: 'default', is_default: true, name: 'Chicken Caesar salad', calories: 430, protein: 35, carbs: 22, fat: 18, vegetarian: false, gluten_free: false, lactose_free: false },
  { id: 'default-17', user_id: 'default', is_default: true, name: 'Greek salad with feta', calories: 380, protein: 16, carbs: 26, fat: 22, vegetarian: true, gluten_free: true, lactose_free: false },
  { id: 'default-18', user_id: 'default', is_default: true, name: 'Smoked salmon salad', calories: 420, protein: 32, carbs: 24, fat: 20, vegetarian: false, gluten_free: true, lactose_free: true },
  { id: 'default-19', user_id: 'default', is_default: true, name: 'Chicken wrap', calories: 450, protein: 38, carbs: 44, fat: 14, vegetarian: false, gluten_free: false, lactose_free: true },
  { id: 'default-20', user_id: 'default', is_default: true, name: 'Veggie wrap with hummus', calories: 420, protein: 16, carbs: 54, fat: 14, vegetarian: true, gluten_free: false, lactose_free: true },
  { id: 'default-21', user_id: 'default', is_default: true, name: 'Ham and cheese sandwich', calories: 360, protein: 24, carbs: 40, fat: 10, vegetarian: false, gluten_free: false, lactose_free: false },
  { id: 'default-22', user_id: 'default', is_default: true, name: 'Peanut butter sandwich', calories: 480, protein: 20, carbs: 50, fat: 22, vegetarian: true, gluten_free: false, lactose_free: true },
  { id: 'default-23', user_id: 'default', is_default: true, name: 'Protein pancakes', calories: 520, protein: 32, carbs: 62, fat: 14, vegetarian: true, gluten_free: false, lactose_free: false },
  { id: 'default-24', user_id: 'default', is_default: true, name: 'Black bean brownie (fit)', calories: 320, protein: 16, carbs: 48, fat: 8, vegetarian: true, gluten_free: true, lactose_free: true },
  { id: 'default-25', user_id: 'default', is_default: true, name: 'Pumpkin cream soup', calories: 360, protein: 10, carbs: 48, fat: 14, vegetarian: true, gluten_free: true, lactose_free: true },
  { id: 'default-26', user_id: 'default', is_default: true, name: 'Chili con carne', calories: 620, protein: 38, carbs: 68, fat: 18, vegetarian: false, gluten_free: true, lactose_free: true },
  { id: 'default-27', user_id: 'default', is_default: true, name: 'Chickpea curry', calories: 560, protein: 20, carbs: 78, fat: 16, vegetarian: true, gluten_free: true, lactose_free: true },
  { id: 'default-28', user_id: 'default', is_default: true, name: 'White fish with potatoes', calories: 500, protein: 38, carbs: 54, fat: 10, vegetarian: false, gluten_free: true, lactose_free: true },
  { id: 'default-29', user_id: 'default', is_default: true, name: 'Pasta with pesto and chicken', calories: 640, protein: 42, carbs: 70, fat: 18, vegetarian: false, gluten_free: false, lactose_free: true },
  { id: 'default-30', user_id: 'default', is_default: true, name: 'Homemade light pizza', calories: 680, protein: 36, carbs: 78, fat: 22, vegetarian: true, gluten_free: false, lactose_free: false },
];
