import { StyleSheet } from 'react-native';
import { theme, type Palette } from '@styles/theme';

export const makeProfileStyles = (palette: Palette) =>
  StyleSheet.create({
    
    sectionCombined: {
      marginHorizontal: 10,
      marginTop: 10,
      padding: 14,
      borderRadius: theme.radius.lg,
      backgroundColor: palette.card,
      borderWidth: 1,
      borderColor: palette.border,
      ...theme.shadow.sm,
    },
    headerRow: {
      alignItems: 'center',
      justifyContent: 'center',
      paddingVertical: 12,
      position: 'relative',
    },
    topRightIcons: {
      position: 'absolute',
      top: 8,
      left: 8,
      flexDirection: 'row',
      alignItems: 'center',
    },
    bellButton: {
      padding: 6,
      position: 'relative',
    },
    badgeDot: {
      position: 'absolute',
      top: 4,
      right: 4,
      width: 10,
      height: 10,
      borderRadius: 5,
      backgroundColor: '#ef4444',
    },
    headerLeft: {
      alignItems: 'center',
      justifyContent: 'center',
    },
    header: {
      alignItems: 'center',
      justifyContent: 'center',
      paddingVertical: 24,
      marginBottom: 8,
      backgroundColor: 'transparent',
    },
    settingsIcon: {
      padding: 6,
      marginLeft: 8,
    },
    avatar: {
      width: 100,
      height: 100,
      borderRadius: 50,
      borderWidth: 3,
      borderColor: theme.colors.primary,
    },
    avatarLarge: {
      width: 120,
      height: 120,
      borderRadius: 60,
      borderWidth: 3,
      borderColor: theme.colors.primary,
    },
    avatarWrapper: {
      width: 120,
      height: 120,
      borderRadius: 60,
      marginBottom: 12,
      overflow: 'hidden',
      alignSelf: 'center',
    },
    avatarUploading: {
      position: 'absolute',
      top: 0,
      left: 0,
      right: 0,
      bottom: 0,
      borderRadius: 60,
      backgroundColor: 'rgba(0,0,0,0.45)',
      alignItems: 'center',
      justifyContent: 'center',
    },
    name: {
      fontSize: 24,
      fontWeight: '700',
      color: palette.text,
    },
    email: {
      fontSize: 16,
      color: palette.subText,
      marginTop: 5,
    },
    section: {
      padding: 10,
      backgroundColor: palette.card,
      paddingVertical: 20,
      margin: 10,
      borderRadius: theme.radius.lg,
      borderColor: palette.border,
      borderWidth: 1,
    },
    sectionTitle: {
      fontSize: 20,
      fontWeight: '600',
      marginBottom: 10,
      color: palette.text,
    },
    bioTitle: {
      fontSize: 20,
      fontWeight: '600',
      color: palette.text,
    },
    postsHeader: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'center',
      marginBottom: 8,
    },
    postsHeaderActions: {
      flexDirection: 'row',
      alignItems: 'center',
    },
    postsActionButton: {
      flexDirection: 'row',
      alignItems: 'center',
      backgroundColor: palette.card100,
      borderRadius: theme.radius.md,
      paddingHorizontal: 12,
      paddingVertical: 8,
      borderWidth: 1,
      borderColor: palette.border,
    },
    postsActionText: {
      marginLeft: 6,
      color: palette.text,
      fontWeight: '600',
      fontSize: 13,
    },
    postsContainer: {
      paddingHorizontal: 12,
      marginTop: 10,
    },
    profileStatsRow: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      marginTop: 8,
      marginBottom: 12,
      paddingHorizontal: 4,
    },
    statRow: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      marginTop: 12,
      marginBottom: 8,
      paddingHorizontal: 4,
    },
    statItem: {
      alignItems: 'center',
      flex: 1,
    },
    statNumber: {
      fontSize: 16,
      fontWeight: '700',
      color: palette.text,
    },
    statLabel: {
      fontSize: 12,
      color: palette.subText,
      marginTop: 4,
    },
    bioBlock: {
      marginTop: 8,
      padding: 14,
      borderRadius: theme.radius.md,
      borderWidth: 1,
      borderColor: palette.border,
      backgroundColor: palette.card100,
    },
    bioBlockFlat: {
      marginTop: 10,
      paddingVertical: 6,
      alignItems: 'center',
    },
    bioHeader: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'center',
      marginBottom: 8,
    },
    bioMetaRow: {
      flexDirection: 'row',
      flexWrap: 'wrap',
      justifyContent: 'center',
      marginTop: 8,
    },
    bioMetaPill: {
      paddingHorizontal: 10,
      paddingVertical: 6,
      borderRadius: theme.radius.sm,
      backgroundColor: palette.card100,
      borderWidth: 1,
      borderColor: palette.border,
      margin: 4,
    },
    bioMetaText: {
      color: palette.text,
      fontSize: 12,
      fontWeight: '600',
    },
    bioEditText: {
      color: palette.primary,
      fontWeight: '700',
      fontSize: 13,
    },
    bioText: {
      color: palette.text,
      fontSize: 14,
      lineHeight: 20,
      textAlign: 'center',
    },
    hashtagsRow: {
      flexDirection: 'row',
      flexWrap: 'wrap',
      marginTop: 8,
      justifyContent: 'center',
    },
    hashtagChip: {
      marginRight: 6,
      marginBottom: 6,
      paddingHorizontal: 10,
      paddingVertical: 6,
      borderRadius: theme.radius.sm,
      backgroundColor: `${palette.primary}14`,
      color: palette.primary,
      fontWeight: '700',
      fontSize: 12,
    },
    linksRow: {
      flexDirection: 'row',
      flexWrap: 'wrap',
      marginTop: 8,
      justifyContent: 'center',
    },
    linkPill: {
      flexDirection: 'row',
      alignItems: 'center',
      paddingHorizontal: 10,
      paddingVertical: 8,
      borderRadius: theme.radius.md,
      borderWidth: 1,
      borderColor: palette.border,
      backgroundColor: palette.card,
      marginRight: 8,
      marginBottom: 8,
    },
    linkText: {
      marginLeft: 8,
      color: palette.text,
      fontWeight: '600',
      fontSize: 13,
    },
    postsMetaRow: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      marginBottom: 12,
      paddingHorizontal: 4,
    },
    postsMetaItem: {
      flex: 1,
      alignItems: 'center',
    },
    postsMetaValue: {
      fontSize: 16,
      fontWeight: '700',
      color: palette.text,
    },
    postsMetaLabel: {
      marginTop: 4,
      color: palette.subText,
      fontSize: 12,
    },
    postsGrid: {
      flexDirection: 'row',
      flexWrap: 'wrap',
      justifyContent: 'space-between',
    },
    postTile: {
      width: '48%',
      minHeight: 220,
      borderRadius: theme.radius.md,
      overflow: 'hidden',
      backgroundColor: palette.card100,
      borderWidth: 1,
      borderColor: palette.border,
      position: 'relative',
      marginBottom: 10,
    },
    achievementsWrapper: {
      paddingHorizontal: 10,
      marginTop: 16,
      marginBottom: 48,
    },
    postTileImage: {
      width: '100%',
      height: 200,
    },
    postTileFallback: {
      flex: 1,
      padding: 10,
      justifyContent: 'center',
      alignItems: 'center',
      backgroundColor: palette.card100,
    },
    postTileFallbackText: {
      color: palette.text,
      fontSize: 12,
      textAlign: 'center',
    },
    postTileOverlay: {
      position: 'absolute',
      bottom: 4,
      right: 4,
      flexDirection: 'row',
      backgroundColor: 'rgba(0,0,0,0.45)',
      borderRadius: theme.radius.sm,
      paddingHorizontal: 6,
      paddingVertical: 4,
      alignItems: 'center',
    },
    postTileOverlayItem: {
      flexDirection: 'row',
      alignItems: 'center',
    },
    postTileOverlayText: {
      color: '#fff',
      fontWeight: '700',
      fontSize: 12,
    },
    commentBar: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      paddingHorizontal: 10,
      paddingVertical: 8,
      borderTopWidth: 1,
      borderTopColor: palette.border,
      backgroundColor: palette.card100,
    },
    commentBarText: {
      color: palette.text,
      fontSize: 12,
      marginLeft: 6,
      flex: 1,
    },
    commentBarAction: {
      color: palette.primary,
      fontWeight: '700',
      fontSize: 12,
    },
    postsEmpty: {
      alignItems: 'center',
      justifyContent: 'center',
      paddingVertical: 20,
    },
    emptyText: {
      color: palette.subText,
      textAlign: 'center',
    },
    fab: {
      position: 'absolute',
      right: 20,
      bottom: 20,
      width: 56,
      height: 56,
      borderRadius: 28,
      backgroundColor: palette.primary,
      justifyContent: 'center',
      alignItems: 'center',
      ...theme.shadow.md,
    },
    inlineSection: {
      paddingTop: 8,
    },
    inlineSectionTitle: {
      fontSize: 16,
      fontWeight: '600',
      marginBottom: 12,
      color: palette.text,
    },
    infoGrid: {
      flexDirection: 'row',
      flexWrap: 'wrap',
      justifyContent: 'space-between',
    },
    infoCard: {
      flexBasis: '48%',
      paddingVertical: 12,
      paddingHorizontal: 12,
      borderRadius: theme.radius.md,
      borderWidth: 1,
      borderColor: palette.border,
      backgroundColor: palette.card100,
      flexDirection: 'row',
      alignItems: 'center',
      marginBottom: 10,
    },
    infoIconWrapper: {
      width: 34,
      height: 34,
      borderRadius: 17,
      backgroundColor: `${palette.primary}14`,
      alignItems: 'center',
      justifyContent: 'center',
      marginRight: 10,
    },
    infoTextWrapper: {
      flex: 1,
    },
    infoLabel: {
      fontSize: 13,
      fontWeight: '600',
      color: palette.text,
    },
    infoValue: {
      fontSize: 13,
      marginTop: 2,
    },
    settingsContainer: {
      marginHorizontal: 4,
      marginTop: 8,
      flexDirection: 'row',
      flexWrap: 'wrap',
      justifyContent: 'space-between',
    },
    inlineSettingsContainer: {
      marginTop: 12,
      flexDirection: 'row',
      flexWrap: 'wrap',
      justifyContent: 'space-between',
    },
    settingsBlock: {
      flexBasis: '48%',
      paddingVertical: 18,
      paddingHorizontal: 16,
      borderRadius: theme.radius.lg,
      backgroundColor: palette.card,
      borderColor: palette.border,
      borderWidth: 1,
      alignItems: 'center',
      ...theme.shadow.sm,
      marginBottom: 12,
    },
    settingsIconWrap: {
      width: 40,
      height: 40,
      borderRadius: 20,
      alignItems: 'center',
      justifyContent: 'center',
    },
    settingsText: {
      marginTop: 12,
      fontSize: 15,
      color: palette.text,
      fontWeight: '600',
      textAlign: 'center',
    },
    settingsValue: {
      marginTop: 6,
      fontSize: 16,
      fontWeight: '600',
      textAlign: 'center',
    },
    settingsHelper: {
      marginTop: 12,
      fontSize: 12,
      fontWeight: '600',
      textTransform: 'uppercase',
      letterSpacing: 0.5,
    },
    optionList: {
      marginTop: 8,
    },
    optionButton: {
      paddingVertical: 12,
      paddingHorizontal: 16,
      borderRadius: theme.radius.sm,
      borderWidth: 1,
      marginTop: 12,
    },
    optionButtonSelected: {
      backgroundColor: theme.colors.primary,
      borderColor: theme.colors.primary,
    },
    optionButtonText: {
      fontSize: 16,
      fontWeight: '500',
    },
    optionGrid: {
      flexDirection: 'row',
      flexWrap: 'wrap',
      marginTop: 8,
    },
    optionScroll: {
      maxHeight: 220,
    },
    optionChip: {
      paddingVertical: 8,
      paddingHorizontal: 14,
      borderRadius: theme.radius.sm,
      borderWidth: 1,
      marginRight: 8,
      marginBottom: 8,
    },
    optionChipSelected: {
      backgroundColor: theme.colors.primary,
      borderColor: theme.colors.primary,
    },
    optionChipText: {
      fontSize: 15,
      fontWeight: '500',
    },
    achievementsList: {
      marginTop: 8,
    },
    achievementCard: {
      flexDirection: 'row',
      alignItems: 'center',
      paddingVertical: 16,
      paddingHorizontal: 18,
      borderRadius: theme.radius.md,
      borderWidth: 1,
      borderColor: palette.border,
      backgroundColor: palette.card,
      ...theme.shadow.sm,
      marginBottom: 12,
    },
    achievementIconWrap: {
      width: 44,
      height: 44,
      borderRadius: 22,
      alignItems: 'center',
      justifyContent: 'center',
      marginRight: 14,
    },
    achievementTextWrap: {
      flex: 1,
    },
    achievementTitle: {
      fontSize: 16,
      fontWeight: '600',
      color: palette.text,
    },
    achievementDescription: {
      marginTop: 6,
      fontSize: 14,
      color: palette.subText,
    },
    achievementBadge: {
      marginTop: 10,
      fontSize: 12,
      fontWeight: '600',
      letterSpacing: 0.5,
      textTransform: 'uppercase',
    },
    friendHeader: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'center',
      marginBottom: 12,
    },
    friendHeaderMeta: {
      flexDirection: 'row',
      alignItems: 'center',
    },
    friendCounter: {
      marginLeft: 10,
      fontSize: 14,
      color: palette.subText,
    },
    friendPreviewGrid: {
      flexDirection: 'row',
      flexWrap: 'wrap',
      justifyContent: 'space-between',
      marginTop: 12,
    },
    friendPreviewCard: {
      flexBasis: '48%',
      flexDirection: 'row',
      alignItems: 'center',
      backgroundColor: palette.card100,
      borderRadius: theme.radius.md,
      borderWidth: 1,
      borderColor: palette.border,
      padding: 10,
      marginBottom: 10,
    },
    friendPreviewText: {
      marginLeft: 10,
      flex: 1,
    },
    friendPreviewName: {
      fontWeight: '600',
      color: palette.text,
    },
    friendPreviewMeta: {
      fontSize: 12,
      color: palette.subText,
      marginTop: 2,
    },
    friendPreviewEmpty: {
      flex: 1,
      textAlign: 'center',
      color: palette.subText,
    },
    friendPreviewMore: {
      marginTop: 4,
      color: palette.subText,
      fontSize: 13,
    },
    friendActionsRow: {
      flexDirection: 'row',
      marginTop: 12,
      justifyContent: 'space-between',
    },
    friendSecondaryButton: {
      flex: 1,
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'center',
      paddingVertical: 12,
      borderRadius: theme.radius.lg,
      borderWidth: 1,
      borderColor: palette.border,
      backgroundColor: palette.card100,
      marginRight: 12,
      ...theme.shadow.sm,
    },
    friendSecondaryButtonLast: {
      marginRight: 0,
    },
    friendSecondaryText: {
      marginLeft: 8,
      fontWeight: '600',
      color: palette.text,
    },
    friendModalOverlay: {
      flex: 1,
      backgroundColor: palette.overlay,
      justifyContent: 'center',
      alignItems: 'stretch',
      paddingHorizontal: 12,
      paddingVertical: 24,
    },
    friendModalCard: {
      flex: 1,
      backgroundColor: palette.card100,
      borderRadius: theme.radius.xl,
      borderWidth: 1,
      borderColor: palette.border,
      padding: 24,
      maxHeight: undefined,
    },
    friendModalHeader: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      marginBottom: 12,
    },
    friendModalTitle: {
      fontSize: 18,
      fontWeight: '700',
      color: palette.text,
    },
    friendModalClose: {
      padding: 6,
    },
    friendModalList: {
      marginTop: 12,
    },
    friendSearchBar: {
      flexDirection: 'row',
      alignItems: 'center',
      borderWidth: 1,
      borderColor: palette.border,
      borderRadius: theme.radius.md,
      backgroundColor: palette.card100,
      paddingHorizontal: 12,
      paddingVertical: 10,
      marginTop: 4,
    },
    friendSearchIcon: {
      marginRight: 8,
    },
    friendSearchInput: {
      flex: 1,
      fontSize: 15,
      color: palette.text,
      paddingVertical: 0,
    },
    friendSuggestionList: {
      marginTop: 16,
    },
    friendListEmpty: {
      paddingVertical: 20,
      textAlign: 'center',
      color: palette.subText,
      fontSize: 14,
    },
    friendRow: {
      flexDirection: 'row',
      alignItems: 'center',
      paddingVertical: 12,
      borderBottomWidth: 1,
      borderBottomColor: palette.border,
    },
    friendRowInfo: {
      flex: 1,
      marginLeft: 12,
    },
    friendRowName: {
      fontSize: 15,
      fontWeight: '600',
      color: palette.text,
    },
    friendRowMeta: {
      fontSize: 13,
      color: palette.subText,
      marginTop: 2,
    },
    friendPrimaryButton: {
      paddingVertical: 8,
      paddingHorizontal: 16,
      borderRadius: theme.radius.sm,
      backgroundColor: palette.primary,
    },
    friendPrimaryButtonText: {
      color: palette.onPrimary,
      fontWeight: '600',
    },
    friendGhostButton: {
      paddingVertical: 8,
      paddingHorizontal: 16,
      borderRadius: theme.radius.sm,
      borderWidth: 1,
      borderColor: palette.border,
      backgroundColor: 'transparent',
    },
    friendGhostButtonText: {
      color: palette.text,
      fontWeight: '600',
    },
    friendStatusPill: {
      flexDirection: 'row',
      alignItems: 'center',
      paddingVertical: 4,
      paddingHorizontal: 10,
      borderRadius: theme.radius.sm,
      backgroundColor: `${palette.primary}1A`,
    },
    friendStatusPillText: {
      marginLeft: 6,
      fontSize: 13,
      color: palette.text,
      fontWeight: '600',
    },
    friendAvatar: {
      width: 44,
      height: 44,
      borderRadius: 22,
      backgroundColor: palette.border,
    },
    friendAvatarSmall: {
      width: 36,
      height: 36,
      borderRadius: 18,
      backgroundColor: palette.border,
    },
    friendNotificationCard: {
      borderWidth: 1,
      borderColor: palette.border,
      borderRadius: theme.radius.md,
      padding: 12,
      backgroundColor: palette.card100,
      marginBottom: 16,
    },
    friendNotificationHeader: {
      flexDirection: 'row',
      alignItems: 'center',
      marginBottom: 10,
    },
    friendNotificationTitle: {
      marginLeft: 6,
      fontSize: 14,
      fontWeight: '600',
      color: palette.text,
    },
    friendNotificationRow: {
      flexDirection: 'row',
      alignItems: 'center',
      marginBottom: 10,
    },
    friendNotificationText: {
      flex: 1,
      marginHorizontal: 10,
    },
    friendNotificationAction: {
      paddingVertical: 6,
      paddingHorizontal: 12,
      borderRadius: theme.radius.sm,
      borderWidth: 1,
      borderColor: palette.border,
    },
    friendNotificationActionText: {
      fontSize: 13,
      fontWeight: '600',
      color: palette.primary,
    },
    friendRequestCard: {
      borderWidth: 1,
      borderColor: palette.border,
      borderRadius: theme.radius.md,
      padding: 12,
      backgroundColor: palette.card100,
      marginBottom: 16,
    },
    friendRequestRow: {
      flexDirection: 'row',
      alignItems: 'center',
      marginTop: 12,
    },
    friendRequestActions: {
      flexDirection: 'row',
      alignItems: 'center',
      marginLeft: 12,
    },
    friendRequestAction: {
      marginLeft: 8,
    },
    modalOverlay: {
      flex: 1,
      backgroundColor: palette.overlay,
      justifyContent: 'center',
      alignItems: 'center',
      padding: 20,
    },
    modalCard: {
      width: '100%',
      maxWidth: 320,
      padding: 20,
      backgroundColor: palette.card,
      borderRadius: theme.radius.md,
      borderColor: palette.border,
      borderWidth: 1,
    },
    modalTitle: {
      fontSize: 20,
      fontWeight: '600',
      marginBottom: 12,
      color: palette.text,
    },
    modalHeaderRow: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      marginBottom: 8,
    },
    notificationItem: {
      flexDirection: 'row',
      alignItems: 'center',
      paddingVertical: 6,
    },
    modalSubtitle: {
      fontSize: 14,
      marginBottom: 16,
      color: palette.subText,
    },
    modalInput: {
      borderWidth: 1,
      borderColor: palette.border,
      borderRadius: theme.radius.sm,
      paddingHorizontal: 12,
      paddingVertical: 10,
      fontSize: 16,
      color: palette.text,
      marginTop: 8,
    },
    modalActions: {
      flexDirection: 'row',
      justifyContent: 'flex-end',
      marginTop: 20,
    },
    modalButton: {
      paddingVertical: 10,
      paddingHorizontal: 16,
      borderRadius: theme.radius.sm,
      borderWidth: 1,
      borderColor: palette.border,
      backgroundColor: palette.card,
      marginLeft: 12,
    },
    modalButtonText: {
      fontSize: 16,
      fontWeight: '500',
      color: palette.text,
    },
    modalPrimaryButton: {
      backgroundColor: theme.colors.primary,
      borderColor: theme.colors.primary,
    },
    modalPrimaryButtonText: {
      fontSize: 16,
      fontWeight: '600',
      color: palette.onPrimary,
    },
    postModalOverlay: {
      flex: 1,
      backgroundColor: palette.overlay,
      justifyContent: 'center',
      paddingHorizontal: 12,
    },
    postModalCard: {
      borderRadius: theme.radius.xl,
      borderWidth: 1,
      padding: 12,
      maxHeight: '90%',
      overflow: 'hidden',
    },
    postModalHeader: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      marginBottom: 8,
    },
  });
