import { StyleSheet } from 'react-native';
import { theme, type Palette } from '@styles/theme';

export const makeProfileStyles = (palette: Palette) =>
  StyleSheet.create({
    
    header: {
      alignItems: 'center',
      paddingVertical: 20,
      margin: 10,
      borderRadius: theme.radius.lg,
      borderColor: palette.border,
      borderWidth: 1,
      backgroundColor: palette.card,
    },
    settingsIcon: {
      position: 'absolute',
      top: 20,
      right: 20,
      padding: 5,
    },
    avatar: {
      width: 100,
      height: 100,
      borderRadius: 50,
      borderWidth: 3,
      borderColor: theme.colors.primary,
    },
    avatarWrapper: {
      width: 100,
      height: 100,
      borderRadius: 50,
      marginBottom: 15,
      overflow: 'hidden',
    },
    avatarUploading: {
      position: 'absolute',
      top: 0,
      left: 0,
      right: 0,
      bottom: 0,
      borderRadius: 50,
      backgroundColor: 'rgba(0,0,0,0.45)',
      alignItems: 'center',
      justifyContent: 'center',
    },
    name: {
      fontSize: 24,
      fontWeight: '700',
      color: palette.text,
    },
    email: {
      fontSize: 16,
      color: palette.subText,
      marginTop: 5,
    },
    section: {
      padding: 10,
      backgroundColor: palette.card,
      paddingVertical: 20,
      margin: 10,
      borderRadius: theme.radius.lg,
      borderColor: palette.border,
      borderWidth: 1,
    },
    sectionTitle: {
      fontSize: 20,
      fontWeight: '600',
      marginBottom: 10,
      color: palette.text,
    },
    inlineSection: {
      paddingTop: 8,
    },
    inlineSectionTitle: {
      fontSize: 16,
      fontWeight: '600',
      marginBottom: 12,
      color: palette.text,
    },
    infoGrid: {
      flexDirection: 'row',
      flexWrap: 'wrap',
      justifyContent: 'space-between',
    },
    infoCard: {
      flexBasis: '48%',
      paddingVertical: 12,
      paddingHorizontal: 12,
      borderRadius: theme.radius.md,
      borderWidth: 1,
      borderColor: palette.border,
      backgroundColor: palette.card100,
      flexDirection: 'row',
      alignItems: 'center',
      marginBottom: 10,
    },
    infoIconWrapper: {
      width: 34,
      height: 34,
      borderRadius: 17,
      backgroundColor: `${palette.primary}14`,
      alignItems: 'center',
      justifyContent: 'center',
      marginRight: 10,
    },
    infoTextWrapper: {
      flex: 1,
    },
    infoLabel: {
      fontSize: 13,
      fontWeight: '600',
      color: palette.text,
    },
    infoValue: {
      fontSize: 13,
      marginTop: 2,
    },
    settingsContainer: {
      marginHorizontal: 4,
      marginTop: 8,
      flexDirection: 'row',
      flexWrap: 'wrap',
      justifyContent: 'space-between',
    },
    inlineSettingsContainer: {
      marginTop: 12,
      flexDirection: 'row',
      flexWrap: 'wrap',
      justifyContent: 'space-between',
    },
    settingsBlock: {
      flexBasis: '48%',
      paddingVertical: 18,
      paddingHorizontal: 16,
      borderRadius: theme.radius.lg,
      backgroundColor: palette.card,
      borderColor: palette.border,
      borderWidth: 1,
      alignItems: 'center',
      ...theme.shadow.sm,
      marginBottom: 12,
    },
    settingsIconWrap: {
      width: 40,
      height: 40,
      borderRadius: 20,
      alignItems: 'center',
      justifyContent: 'center',
    },
    settingsText: {
      marginTop: 12,
      fontSize: 15,
      color: palette.text,
      fontWeight: '600',
      textAlign: 'center',
    },
    settingsValue: {
      marginTop: 6,
      fontSize: 16,
      fontWeight: '600',
      textAlign: 'center',
    },
    settingsHelper: {
      marginTop: 12,
      fontSize: 12,
      fontWeight: '600',
      textTransform: 'uppercase',
      letterSpacing: 0.5,
    },
    optionList: {
      marginTop: 8,
    },
    optionButton: {
      paddingVertical: 12,
      paddingHorizontal: 16,
      borderRadius: theme.radius.sm,
      borderWidth: 1,
      marginTop: 12,
    },
    optionButtonSelected: {
      backgroundColor: theme.colors.primary,
      borderColor: theme.colors.primary,
    },
    optionButtonText: {
      fontSize: 16,
      fontWeight: '500',
    },
    optionGrid: {
      flexDirection: 'row',
      flexWrap: 'wrap',
      marginTop: 8,
    },
    optionScroll: {
      maxHeight: 220,
    },
    optionChip: {
      paddingVertical: 8,
      paddingHorizontal: 14,
      borderRadius: theme.radius.sm,
      borderWidth: 1,
      marginRight: 8,
      marginBottom: 8,
    },
    optionChipSelected: {
      backgroundColor: theme.colors.primary,
      borderColor: theme.colors.primary,
    },
    optionChipText: {
      fontSize: 15,
      fontWeight: '500',
    },
    achievementsList: {
      marginTop: 8,
    },
    achievementCard: {
      flexDirection: 'row',
      alignItems: 'center',
      paddingVertical: 16,
      paddingHorizontal: 18,
      borderRadius: theme.radius.md,
      borderWidth: 1,
      borderColor: palette.border,
      backgroundColor: palette.card,
      ...theme.shadow.sm,
      marginBottom: 12,
    },
    achievementIconWrap: {
      width: 44,
      height: 44,
      borderRadius: 22,
      alignItems: 'center',
      justifyContent: 'center',
      marginRight: 14,
    },
    achievementTextWrap: {
      flex: 1,
    },
    achievementTitle: {
      fontSize: 16,
      fontWeight: '600',
      color: palette.text,
    },
    achievementDescription: {
      marginTop: 6,
      fontSize: 14,
      color: palette.subText,
    },
    achievementBadge: {
      marginTop: 10,
      fontSize: 12,
      fontWeight: '600',
      letterSpacing: 0.5,
      textTransform: 'uppercase',
    },
    modalOverlay: {
      flex: 1,
      backgroundColor: palette.overlay,
      justifyContent: 'center',
      alignItems: 'center',
      padding: 20,
    },
    modalCard: {
      width: '100%',
      maxWidth: 320,
      padding: 20,
      backgroundColor: palette.card,
      borderRadius: theme.radius.md,
      borderColor: palette.border,
      borderWidth: 1,
    },
    modalTitle: {
      fontSize: 20,
      fontWeight: '600',
      marginBottom: 12,
      color: palette.text,
    },
    modalSubtitle: {
      fontSize: 14,
      marginBottom: 16,
      color: palette.subText,
    },
    modalInput: {
      borderWidth: 1,
      borderColor: palette.border,
      borderRadius: theme.radius.sm,
      paddingHorizontal: 12,
      paddingVertical: 10,
      fontSize: 16,
      color: palette.text,
      marginTop: 8,
    },
    modalActions: {
      flexDirection: 'row',
      justifyContent: 'flex-end',
      marginTop: 20,
    },
    modalButton: {
      paddingVertical: 10,
      paddingHorizontal: 16,
      borderRadius: theme.radius.sm,
      borderWidth: 1,
      borderColor: palette.border,
      backgroundColor: palette.card,
      marginLeft: 12,
    },
    modalButtonText: {
      fontSize: 16,
      fontWeight: '500',
      color: palette.text,
    },
    modalPrimaryButton: {
      backgroundColor: theme.colors.primary,
      borderColor: theme.colors.primary,
    },
    modalPrimaryButtonText: {
      fontSize: 16,
      fontWeight: '600',
      color: palette.onPrimary,
    },
  });
